package com.sedsoftware.nxmods.network.stubs.responses

import com.sedsoftware.nxmods.network.models.ModInfoModel
import com.sedsoftware.nxmods.network.stubs.Utils

internal object GetModsList {

    val response: List<ModInfoModel>
        get() = Utils.decodeFromJson(json)

    private val json = """
        [
            {
                "name": "Cyber Engine Tweaks",
                "summary": "Scripting framework for modders and quality of life fixes.",
                "description": "[b][url=https://wiki.cybermods.net/cyber-engine-tweaks/][u][size=3]Please read the Wiki![/size][/u]\n<br />[/url]\n<br />[/b][b]Cyber Engine Tweaks[/b] is a framework giving modders a way to script mods using [url=https://www.lua.org/]Lua [/url]with access to all the internal scripting features, it also comes with a UI to configure the different mods you are using or using the console directly. It also adds some in game patches for quality of life (for example it fixed the security flaw that was then fixed with the 1.12 patch of the game), all of which can be enabled/disabled through the settings menu or config files.\n<br />\n<br />As it stands the recommended method of installation is manual installation, however you can use vortex.\n<br /> When installing through vortex, make sure to use hardlink deployment.\n<br />If you wish to install manually please read the instructions on the [url=https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing]wiki [/url].\n<br />\n<br />No support will be provided here by developers, if you need help join us on [url=https://discord.gg/Epkq79kd96]discord [/url]﻿after having read the troubleshooting guide on the [url=https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing/troubleshooting]wiki[/url]. Issues posted here are also not considered, if you want to report a bug do so [url=https://github.com/yamashi/CyberEngineTweaks/issues]here[/url]﻿. This is for posting actual bugs, not user error. \n<br />\n<br />If you are a C++ developer and/or reverse engineer, you can contribute on [url=https://github.com/yamashi/CyberEngineTweaks]github[/url].\n<br />\n<br />[size=4][b]Supported version:[/b] [color=#00ffff][b]1.61[/b][/color][/size]\n<br />[b]\n<br />Bitcoin[/b]: bc1q0neujk5e8v8sc3934ajn8z8zav7hl6557fjj54\n<br />[b]Bitcoin Cash[/b]: qps5ze9p8fxmu4rszyxwy3g0ctlmrhvc3uqq0fzsnl\n<br />[b]Dogecoin[/b]: DMoReR33D87D6rYeUkyQb2BsEHJTqfBFva\n<br />[b]Ethereum[/b]: 0x7Cd23BE1C507Da85ABF0B05c7A3C03e6d3d0233B\n<br />[b]Patreon[/b]: [url=https://www.patreon.com/tiltedphoques]https://www.patreon.com/tiltedphoques\n<br />\n<br />[/url]Thanks everyone for the donations, your support means a lot! A special shout-out to the anonymous bitcoin donator, you are crazy!",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/107/107-1613641770-185635979.png",
                "mod_downloads": 3677578,
                "mod_unique_downloads": 1420301,
                "uid": 14315125997675,
                "mod_id": 107,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "1.21.1",
                "endorsement_count": 59562,
                "created_timestamp": 1607812774,
                "created_time": "2020-12-12T22:39:34.000+00:00",
                "updated_timestamp": 1668271994,
                "updated_time": "2022-11-12T16:53:14.000+00:00",
                "author": "yamashi",
                "uploaded_by": "awpsoleet",
                "uploaded_users_profile_url": "https://nexusmods.com/users/3386513",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 3386513,
                    "member_group_id": 27,
                    "name": "awpsoleet"
                },
                "endorsement": null
            },
            {
                "name": "redscript",
                "summary": "Compiler for Cyberpunk2077 scripts",
                "description": "[img]https://user-images.githubusercontent.com/11986158/145491396-b987a964-4b45-460c-8864-9a78ebdff529.png[/img]\n<br />\n<br />[size=4][b]REDSCRIPT[/b][/size]\n<br />\n<br />This is a script compiler that can be integrated with the game and used to add/replace game scripts.\n<br />Source code available [url=https://github.com/jac3km4/redscript]here[/url].\n<br />\n<br />[b]INSTALLATION[/b]\n<br />You'll need to download the archive available in the 'Files' tab and extract it in the main 'Cyberpunk 2077' directory.\n<br />You should end up with the following files in the game directory:\n<br />- Cyberpunk 2077&#92;engine&#92;tools&#92;scc.exe\n<br />- Cyberpunk 2077&#92;engine&#92;config&#92;base&#92;scripts.ini\n<br />\n<br />[b]NOTE FOR REDMOD USERS\n<br />[/b]If you want to use redscript along with redmod, you should install [url=https://www.nexusmods.com/cyberpunk2077/mods/5176]cybercmd[/url]﻿, it solves an issue where the redmod launcher would disable redscript compilation. The redscript mod archive contains configuration which will get picked up by cybercmd automatically once installed.\n<br />\n<br />[b]NOT WORKING?\n<br />[/b]If you are not sure if it's working or have any other issues, you should look for a log file at 'Cyberpunk 2077&#92;r6&#92;logs&#92;redscript.log'.\n<br />This log file should end with 'Output successfully saved to ...' if the mods were applied successfully.\n<br />If the log file contains any errors or warnings, you can post them here to help with debugging.\n<br />If the log file isn't there, redscript has not been installed correctly.\n<br />\n<br />[b]UNINSTALLING[/b]\n<br />The compiler saves a copy of the game scripts in a file 'Cyberpunk 2077&#92;r6&#92;cache&#92;final.redscripts.bk'.\n<br />If you wish to uninstall redscript you can just remove the files you downloaded (scc.exe and scripts.ini) and replace the existing 'final.redscripts' with the backed up 'final.redscripts.bk' file.",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/1511/1511-1612727913-1059595445.png",
                "mod_downloads": 1665300,
                "mod_unique_downloads": 829758,
                "uid": 14315125999079,
                "mod_id": 1511,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "0.5.8",
                "endorsement_count": 27738,
                "created_timestamp": 1612727972,
                "created_time": "2021-02-07T19:59:32.000+00:00",
                "updated_timestamp": 1663418970,
                "updated_time": "2022-09-17T12:49:30.000+00:00",
                "author": "jac3km4",
                "uploaded_by": "jac3km4",
                "uploaded_users_profile_url": "https://nexusmods.com/users/49982271",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 49982271,
                    "member_group_id": 30,
                    "name": "jac3km4"
                },
                "endorsement": null
            },
            {
                "name": "RED4ext",
                "summary": "A script extender for REDengine 4.",
                "description": "RED4ext is a library that extends REDengine 4. It will allow modders to add new features, modify the game behavior, add new scripting functions or call existing ones in your own plugins.\n<br />\n<br />This library is similar to:\n<br />[list]\n<br />[*][url=http://dev-c.com/GTAV/scripthookv]Script Hook V[/url]\n<br />[*][url=https://skse.silverlock.org/]Skyrim Script Extender[/url]\n<br />[/list]\n<br />This library is split into two parts:\n<br />[list]\n<br />[*][url=https://github.com/WopsS/RED4ext]RED4ext[/url] - This project which consist of the loader, it only takes care of managing plugins.\n<br />[*][url=https://github.com/WopsS/RED4ext.SDK]RED4ext.SDK[/url] - This project contains the reversed types and helpers to extend the engine, it can be used independently of RED4ext.\n<br />[/list]\n<br />If you are developing a new plugin, add only [url=https://github.com/WopsS/RED4ext.SDK]RED4ext.SDK[/url] in your project structure.\n<br />\n<br />[size=4]Installing[/size]\n<br />\n<br />[list=1]\n<br />[*][b][/b][b][/b][b]Download [/b]the latest zip (e.g. [b]red4ext_x.y.z.zip[/b]) from [url=https://github.com/WopsS/RED4ext/releases/latest]GitHub [/url]﻿or [url=https://www.nexusmods.com/cyberpunk2077/mods/2380]NexusMods[/url]﻿.\n<br />[*][b]Extract [/b]the content of the archive in the game's directory.\n<br />[*][b]Launch [/b]the game.\n<br />[*]([b]Optional[/b]) Check the log file in [b]&lt;game_directory&gt;/red4ext/logs/red4ext.log[/b] to make sure everything works.\n<br />[/list]\n<br />[size=4]Uninstall[/size]\n<br />\n<br />[list=1]\n<br />[*]Remove [b]d3d11.dll[/b] / [b]powrprof.dll[/b] from [b]&lt;game_directory&gt;/bin/x64[/b].\n<br />[*]([b]Optionally[/b]) Remove [b]red4ext [/b]directory from [b]&lt;game_directory&gt;[/b].\n<br />[/list]\n<br />The complete / most up to date documentation is now available at [url=https://docs.red4ext.com]docs.red4ext.com[/url].",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/2380/2380-1618829826-1376548256.png",
                "mod_downloads": 887365,
                "mod_unique_downloads": 517305,
                "uid": 14315125999948,
                "mod_id": 2380,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "1.9.0",
                "endorsement_count": 12937,
                "created_timestamp": 1618832883,
                "created_time": "2021-04-19T11:48:03.000+00:00",
                "updated_timestamp": 1667929438,
                "updated_time": "2022-11-08T17:43:58.000+00:00",
                "author": "WopsS",
                "uploaded_by": "WopsS",
                "uploaded_users_profile_url": "https://nexusmods.com/users/16475274",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 16475274,
                    "member_group_id": 3,
                    "name": "WopsS"
                },
                "endorsement": null
            },
            {
                "name": "ArchiveXL",
                "summary": "Archive extension loader",
                "description": "[color=#f3e500][size=6]ArchiveXL[/size][/color]\n<br />[size=3]\n<br />— Load custom entity factories (necessary for item additions)\n<br />— Add localization texts that can be used in scripts, resources and TweakDB\n<br />— Edit existing localization texts without overwriting original resources\n<br />— Override submeshes visibility of entity parts\n<br />— Add visual tags to a clothing item\n<br />— Spawn widgets from any library without registering dependencies\n<br />[/size]\n<br />[color=#f24e48][size=6]Getting Started[/size][/color]\n<br />\n<br />[size=5]Requirements[/size]\n<br />\n<br />[size=3]— Cyberpunk 2077 1.61[/size]\n<br />[size=3]— [url=https://www.nexusmods.com/cyberpunk2077/mods/2380]RED4ext[/url] 1.9.0+[/size]\n<br />\n<br />[size=5]Installation[/size]\n<br />\n<br />[size=3]1. Download the latest release[/size]\n<br />[size=3]2. Extract the archive into the Cyberpunk 2077 directory[/size]\n<br />\n<br />[size=2][color=#aaaaaa][i]You should have a \"&lt;Cyberpunk 2077&gt;/red4ext/plugins/ArchiveXL\" directory if done correctly.[/i][/color][/size]\n<br />\n<br />[color=#f24e48][size=6]Documentation[/size][/color]\n<br />[size=3]\n<br />▸ [url=https://github.com/psiberx/cp2077-archive-xl#extending-resources]Extending resources[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-archive-xl#overriding-submeshes]Overriding submeshes[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-archive-xl#adding-visual-tags]Adding visual tags[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-archive-xl#spawning-widgets]Spawning widgets[/url]\n<br />[/size]\n<br />[color=#f24e48][size=6]Community[/size][/color]\n<br />[size=3][size=3]\n<br />If you need help with mod development or have any other question, please feel free to contact me on Discord.\n<br />I prefer public discussions so that everyone can use shared knowledge.\n<br />[/size]\n<br />▸ [url=https://discord.gg/KdBvAha3ca]Cyberpunk 2077 Modding Community[/url]\n<br />▸ [url=https://discord.gg/z3dBY7PQNK]Cyberpunk 2077 Modding[/url]\n<br />[/size]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/4198/4198-1648116857-72076015.jpeg",
                "mod_downloads": 674663,
                "mod_unique_downloads": 414436,
                "uid": 14315126001766,
                "mod_id": 4198,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "1.1.6",
                "endorsement_count": 10083,
                "created_timestamp": 1648124529,
                "created_time": "2022-03-24T12:22:09.000+00:00",
                "updated_timestamp": 1667930607,
                "updated_time": "2022-11-08T18:03:27.000+00:00",
                "author": "psiberx",
                "uploaded_by": "psiberx",
                "uploaded_users_profile_url": "https://nexusmods.com/users/108159138",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 108159138,
                    "member_group_id": 30,
                    "name": "psiberx"
                },
                "endorsement": null
            },
            {
                "name": "TweakXL",
                "summary": "TweakDB modifications loader and script extensions",
                "description": "[color=#f3e500][size=6]TweakXL[/size][/color]\n<br />[size=3]\n<br />— Create TweakDB mods using YAML format\n<br />— Access and modify TweakDB from scripts\n<br />[/size]\n<br />[color=#f24e48][size=6]Getting Started[/size][/color]\n<br />\n<br />[size=5]Requirements[/size]\n<br />\n<br />[size=3]— Cyberpunk 2077 1.61[/size]\n<br />[size=3]— [url=https://www.nexusmods.com/cyberpunk2077/mods/2380]RED4ext[/url] 1.9.0+[/size]\n<br />\n<br />[size=5]Installation[/size]\n<br />\n<br />[size=3]1. Download the latest release[/size]\n<br />[size=3]2. Extract the archive into the Cyberpunk 2077 directory[/size]\n<br />\n<br />[size=2][color=#aaaaaa][i]You should have a \"&lt;Cyberpunk 2077&gt;/red4ext/plugins/TweakXL\" directory if done correctly.[/i][/color][/size]\n<br />\n<br />[color=#f24e48][size=6]Documentation[/size][/color]\n<br />[size=3]\n<br />▸ [url=https://github.com/psiberx/cp2077-tweak-xl/wiki/About-TweakDB]About TweakDB[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-tweak-xl/wiki/YAML-Tweaks]YAML Tweaks[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-tweak-xl/wiki/Script-Extensions]Script Extensions[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-tweak-xl/wiki/Modder-Tools]Modder Tools[/url]\n<br />▸ [url=https://github.com/psiberx/cp2077-tweak-xl/wiki/Examples]Examples[/url]\n<br />[/size]\n<br />[color=#f24e48][size=6]Community[/size][/color]\n<br />[size=3]\n<br />If you need help with mod development or have any other question, please feel free to contact me on Discord.\n<br />I prefer public discussions so that everyone can use shared knowledge.\n<br />\n<br />▸ [url=https://discord.gg/KdBvAha3ca]Cyberpunk 2077 Modding Community[/url]\n<br />▸ [url=https://discord.gg/z3dBY7PQNK]Cyberpunk 2077 Modding[/url]\n<br />[/size]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/4197/4197-1648116989-1847614261.jpeg",
                "mod_downloads": 656885,
                "mod_unique_downloads": 417594,
                "uid": 14315126001765,
                "mod_id": 4197,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "1.0.8",
                "endorsement_count": 9892,
                "created_timestamp": 1648124513,
                "created_time": "2022-03-24T12:21:53.000+00:00",
                "updated_timestamp": 1667930610,
                "updated_time": "2022-11-08T18:03:30.000+00:00",
                "author": "psiberx",
                "uploaded_by": "psiberx",
                "uploaded_users_profile_url": "https://nexusmods.com/users/108159138",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 108159138,
                    "member_group_id": 30,
                    "name": "psiberx"
                },
                "endorsement": null
            },
            {
                "name": "Native Settings UI",
                "summary": "This mod allows other mods to easily add settings menus using only native UI, thus looking like the games settings menu",
                "description": "[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/main.gif[/img]\n<br />[b][i][color=#ff00ff][b][u][color=#00ff00][size=4][b][u][color=#00ff00][size=4][i][url=https://www.buymeacoffee.com/keanuWheeze]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze@main/buymeacoffee.png[/img][/url][/i][/size][/color][/u][/b][/size][/color][/u][/b][/color][/i][/b]\n<br />\n<br />[color=#00ff00][size=4][b][u]What it does:\n<br />[/u][/b][/size][/color]- Lets other mods add their own page and add settings widgets to the newly added \"Mods\" settings menu\n<br />- Easy to use, and useful features such as option descriptions and resetting to default values\n<br />- Looks and behaves just like the normal settings menu\n<br />- Fully compatible with controllers (Obviously)\n<br />- Offers adding of new tabs and subcategories. Widgets are switches, sliders, list selectors, keybinds and buttons\n<br />\n<br />[color=#ff0000][size=4][b][u]What it does not:\n<br />[/u][/b][/size][/color]- Offer a way of saving the settings or anything like that, this mod just provides the UI, what you do with it is up to you\n<br />\n<br />[color=#00ffff][size=4][b][u]Installation:\n<br />[/u][/b][/size][/color]- Download the [b][color=#ff0000]LATEST [/color][/b]version of [url=https://www.nexusmods.com/cyberpunk2077/mods/107]CET[/url]\n<br />- Extract this mod into your base game folder (The one containing /bin)\n<br />\n<br />[color=#00ff00][size=4][u][b]For modders:\n<br />[/b][/u][/size][/color]- If you want to use this mod, just add it to your mod's requirement list and nexus will prompt the user to download it[color=#ff0000][size=4][b][u]\n<br />[/u][/b][/size][/color]- For documentation and examples on how to add your own menu, please visit:\n<br />[center][color=#ff0000][b][url=https://github.com/justarandomguyintheinternet/CP77_nativeSettings][size=6]This mods GitHub Page[/size][/url][size=5]﻿[/size][/b][/color][/center]- Also feel free to ask me on the CP2077 Modding Discord\n<br />[color=#00ffff][size=3][b][u]\n<br />Available widgets:\n<br />\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/tabs.gif[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/sub.PNG[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/switch.gif[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/int.gif[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/float.gif[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/list.gif[/img]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/keybind.gif[/img][/u][/b][/size][/color]\n<br />[img]https://cdn.jsdelivr.net/gh/justarandomguyintheinternet/keanuWheeze/nativeSettingsImages/button.gif[/img]\n<br />\n<br />[b][color=#00ff00][size=4][u]\n<br />Credits:\n<br />[/u][/size][/color][/b][size=3][color=#00ff00][b][list]\n<br />[*][url=https://github.com/psiberx]psiberx[/url] for answering all my questions, as well as doing a lot of work on CET that makes this mod even work and creating Cron.lua,, UIButton.lua, Ref.lua and EventProxy.lua\n<br />[*]rmk for testing and helping me with bugfixing &lt;3\n<br />[/list][list]\n<br />[*]nim for hating ImGui\n<br />[/list][/b][/color][/size]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/3518/3518-1638213207-1484439585.png",
                "mod_downloads": 775006,
                "mod_unique_downloads": 473159,
                "uid": 14315126001086,
                "mod_id": 3518,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 12,
                "version": "1.9",
                "endorsement_count": 13613,
                "created_timestamp": 1638634595,
                "created_time": "2021-12-04T16:16:35.000+00:00",
                "updated_timestamp": 1662578960,
                "updated_time": "2022-09-07T19:29:20.000+00:00",
                "author": "keanuWheeze",
                "uploaded_by": "NexusGuy999",
                "uploaded_users_profile_url": "https://nexusmods.com/users/77476393",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 77476393,
                    "member_group_id": 3,
                    "name": "NexusGuy999"
                },
                "endorsement": null
            },
            {
                "name": "Mod Settings",
                "summary": "Adds a redscript-configurable \"Mod Settings\" page to the main menu that any mod can add a page to.",
                "description": "Installation:\n<br />Install the requirements, and place the contents of mod_settings.zip directly into to your game's installation folder.\n<br />\n<br />Allows mods to configure a tab under \"Mod Settings\" in the main menu, using only redscript. For an example, see here: https://github.com/jackhumbert/in_world_navigation/blob/main/src/redscript/in_world_navigation/InWorldNavigation.reds",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/4885/4885-1658548659-1491857712.jpeg",
                "mod_downloads": 443020,
                "mod_unique_downloads": 291422,
                "uid": 14315126002453,
                "mod_id": 4885,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 8,
                "version": "0.0.9",
                "endorsement_count": 5893,
                "created_timestamp": 1658548961,
                "created_time": "2022-07-23T04:02:41.000+00:00",
                "updated_timestamp": 1668045078,
                "updated_time": "2022-11-10T01:51:18.000+00:00",
                "author": "Jack Humbert",
                "uploaded_by": "jackhumbert",
                "uploaded_users_profile_url": "https://nexusmods.com/users/86010988",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 86010988,
                    "member_group_id": 27,
                    "name": "jackhumbert"
                },
                "endorsement": null
            },
            {
                "name": "Material and Texture Override",
                "summary": "Enables the game to load new materials. But it's REDmod compatible now. Please read the description.",
                "description": "[center][url=https://ko-fi.com/aarunim][img]https://uploads-ssl.webflow.com/5c14e387dab576fe667689cf/5c91bddac6c3aa6b3718fd86_kofisvglofo.svg[/img][/url]﻿[size=1][i]\n<br />Mmm coffee.[/i][/size][size=1][i]\n<br />\n<br />[/i][/size][/center][s]\n<br />[/s][center][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#b6b6b6][b]tldr:[/b][/color]\n<br />[color=#666666][/color][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color][s]\n<br />[/s][/center][s]\n<br />[/s][center][size=2]Install the main file in [color=#666666][color=#ffffff][color=#00ffff]Cyberpunk 2077&#92;mods[/color][/color][/color], remove any other instances of [color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#00ffff]nim_material_override.archive[/color][/color][/color][/color][/color][/color][/color] you may have in [color=#00ffff]archive&#92;pc&#92;mod[/color], then toggle and deploy the new version with REDmod.[/size][s][s]\n<br />\n<br />[/s][/s][size=2]Have a nice day.[/size][s][s][/s][/s][/center][s][s]\n<br />[/s]\n<br />[/s][center][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#b6b6b6][b]What:[/b][/color]\n<br />[color=#666666][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#ffffff][size=2][/size][/color][/color][/center][color=#666666][color=#ffffff][size=2]\n<br />[/size][/color][/color][center][size=2]This archive enables the game to load new materials and textures[color=#cccccc]*[/color], it is required by everything and anything that uses new files of this type.\n<br />\n<br />This file is future proof, there should be no reason to update it for new patches, given they do not drastically change the way materials are indexed by the game.[/size]\n<br />\n<br />[color=#cccccc][size=1]*Replacement textures do not themselves require this archive provided they are not loaded by the various material file types used by items or objects, texture files loaded anywhere in a new material file chain will however require this archive, as will new material files, due to the game not having indexed them.[/size][/color][/center]\n<br />\n<br />[center][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#b6b6b6][b]Why:[/b][/color]\n<br />[color=#666666][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[/color][/center][color=#666666]\n<br />[color=#ffffff][center][size=2]The game typically cannot load anything that is not present in it's material database, this is obviously an issue for modders. \n<br />\n<br />Having duplicates of this file has caused issues in the past and the need for a single dedicated file arose, hi.[/size][/center]\n<br />\n<br />[center][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#b6b6b6][b]Installation:[/b][/color]\n<br />[color=#666666][/color][color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color][/center][center]\n<br />[size=2][size=3][color=#00ff00]1.[/color] [/size]Drag and drop the contents of [color=#00ffff][color=#ffffff]the [/color]Material and Texture Override.7z[/color] file into your [color=#00ffff]Cyberpunk 2077&#92;mods[/color] folder.\n<br />[size=1]\n<br />[color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#666666][color=#ffffff].7z files can be opened with [url=https://www.7-zip.org/download.html]7-zip[/url] if that information is required.[/color][/color][/color][/color][/color][/color]\n<br />\n<br />You should now have: \n<br />- [color=#00ffff]Cyberpunk 2077&#92;mods&#92;Material and Texture Override&#92;archives&#92;###_nim_material_override.archive[/color]\n<br />[color=#666666][color=#ffffff]- [color=#00ffff]Cyberpunk 2077&#92;mods&#92;Material and Texture Override&#92;[/color][/color][/color][color=#00ffff]info.json[/color]\n<br />[/size]\n<br />[color=#00ff00][size=3]2.[/size][/color] Toggle and deploy it with REDmod.\n<br />\n<br />[color=#666666][color=#ffffff][size=2][color=#00ff00][size=3]3.[/size][/color] [/size][/color][/color]The old nexus page's archive file, which you will need to remove manually from [color=#00ffff]/archive/pc/mod[/color], is named [color=#00ffff]00_nim_material_override.archive[/color][/size]\n<br />[size=2]\n<br />[size=1]Other possible archive file names depending where you first acquired it:\n<br />- [color=#00ffff]basegame_0_a_nim_material_override.archive[/color]\n<br />- [color=#666666][color=#ffffff][color=#00ffff]basegame_nim_material_override.archive[/color][/color][/color]\n<br />- [color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#00ffff]nim_material_override.archive[/color][/color][/color][/color][/color]\n<br />- Any other archive file you may have that contains [/size][color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#00ffff][size=1]nim_material_override[/size][color=#ffffff][size=1], or even [color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#666666][color=#ffffff][color=#00ffff]material_override[/color][/color][/color][/color][/color][/color][/color] in it's file name.[/size]\n<br />[/color][/color][/color][/color][/color][/color][/size]\n<br />[color=#666666][color=#ffffff][size=2][color=#00ff00]Mods making use of the old archive will continue to work with this new format provided you have installed REDmod correctly and the new archive is in fact loading.\n<br />\n<br />[/color][/size][/color][/color][/center][center][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color]\n<br />[color=#b6b6b6][b]Why the update and new mod page:[/b][/color]\n<br />[color=#666666][/color][color=#666666][color=#ffffff][color=#666666][/color][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/center]\n<br />[center][size=2]REDmod is weird, and because I am now actively using nexus and can post things myself, respectively.\n<br />\n<br />Also due to the old mod directory structure being removed eventually and [size=2]REDmod[/size]'s structure becoming the new standard.\n<br />\n<br />This file will not be relocated again, apologies to those that have to update their mod page's requirements, though this is not strictly necessary as the old page now has a direct link to this page, I do still apologise.\n<br />\n<br />If you do not yet use [size=2][size=2]REDmod[/size][/size], you should start now, as it will apparently soon be the only way to load archive mods.\n<br />\n<br />The original page is [url=https://www.nexusmods.com/cyberpunk2077/mods/1572]here[/url] if that is for some reason required, the file on this old page has now been removed, the page itself however will remain for the purpose of redirection to this new page.[/size]\n<br />\n<br />[color=#666666][color=#ffffff][size=2]If you for some reason require the old directory structure, there is a legacy version available in [color=#00ffff]optional files[/color]. To install the legacy version, drag and drop the contents of [color=#00ffff]Original File.7z[/color] into your [color=#00ffff]Cyberpunk 2077 root directory[/color] as you would any mod not set up for REDmod.\n<br />\n<br />[color=#666666][color=#ffffff][size=2][size=1]You should now have (legacy version only): \n<br />- [color=#00ffff]Cyberpunk 2077&#92;archive&#92;pc&#92;mod&#92;###_nim_material_override.archive[/color][/size][/size][/color][/color][/size][/color][/color]\n<br />\n<br />[color=#00ff00][size=2]Do NOT install both the REDmod compatible version and legacy version of this mod at the same time.[/size][/color]\n<br />\n<br />[size=2]If I have missed something and you are still confused about what this file does or how to install it, please refer to the comments section, and browse other users comments before posting your issue, it is likely to have already been answered by myself or another user.[/size]\n<br />\n<br />[size=2]If you have read all of this I am very proud of you, have a great day.\n<br />\n<br />\n<br />[size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size]\n<br />[color=#b6b6b6][b]Compatibility History:[/b][/color][/size][/center][center][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size]\n<br />[size=2]\n<br />[/size][color=#00ff00][size=2]- Working as of 1.6[/size][/color]\n<br />\n<br />\n<br />[color=#666666][color=#ffffff][color=#666666][color=#ffffff][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/color][/color][/color]\n<br />[color=#b6b6b6][b]Credits:[/b][/color]\n<br />[color=#666666][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/color][/center]\n<br />[/color][/color][center][color=#666666][color=#ffffff][size=2][url=https://www.nexusmods.com/users/51984341]Nim[/url]:\n<br />I did things.\n<br />\n<br />[url=https://www.nexusmods.com/cyberpunk2077/users/26505]Faeryn/[/url][url=https://www.nexusmods.com/cyberpunk2077/users/26505]Earrindo[/url]:\n<br />[/size][/color][/color][size=2]For the original upload and maintaining updates.\n<br />\n<br />[url=https://www.nexusmods.com/cyberpunk2077/users/3046671]ArsenicTouch[/url]﻿:\n<br />For testing, making it work with [color=#666666][color=#ffffff]REDmod[/color][/color][color=#666666][color=#ffffff], and making me panic.\n<br />\n<br />[url=https://cdn.shopify.com/s/files/1/0028/6916/6192/products/Clown_emoji_1200x1200.png?v=1580073477]NexusMods[/url]:\n<br />[/color][/color]For making me crazy.[/size][/center]\n<br />\n<br />[center][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size]\n<br />\n<br />[size=2]Please consider [url=https://ko-fi.com/aarunim]supporting me[/url]﻿ if you find use in what I do, and remember to smile today.\n<br />\n<br />[/size][size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size]\n<br />[size=4][size=2]\n<br />If you are interested in learning more about modding Cyberpunk, join us over at [url=https://discord.com/invite/BTApCbE]DISCORD[/url]. We'll help out where we can if we are alive at the time.\n<br />[/size][/size]\n<br />[size=4][size=2][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-------------------------------------------------------------[/color][/color][/color][color=#666666][color=#ffffff][color=#666666]-----------------------------------------------------[/color][/color][/color][/color][/color][/color][/size][/size][/center][url=https://discord.com/invite/BTApCbE][img]https://i.imgur.com/0pqEiU0.gif[/img][/url]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/5266/5266-1663479835-149434627.png",
                "mod_downloads": 308341,
                "mod_unique_downloads": 215826,
                "uid": 14315126002834,
                "mod_id": 5266,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 9,
                "version": "1.1",
                "endorsement_count": 5343,
                "created_timestamp": 1663482289,
                "created_time": "2022-09-18T06:24:49.000+00:00",
                "updated_timestamp": 1663492843,
                "updated_time": "2022-09-18T09:20:43.000+00:00",
                "author": "Nim",
                "uploaded_by": "NimRain",
                "uploaded_users_profile_url": "https://nexusmods.com/users/51984341",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 51984341,
                    "member_group_id": 3,
                    "name": "NimRain"
                },
                "endorsement": null
            },
            {
                "name": "Input Loader",
                "summary": "This plugin looks for all r6/input/*.xml files and merges them with the appropriate input config file from r6/config/ and saves results to r6/cache/. A configuration file is written to engine/config/platform/pc/input_loader.ini, which tells the game to load the merged .xml files.",
                "description": "[size=5]Cyberpunk 2077 Input Loader\n<br />\n<br />[/size][url=https://github.com/jackhumbert/cyberpunk2077-input-loader]Github page[/url]\n<br />\n<br />This plugin looks for all `r6/input/*.xml` files and merges them with the appropriate input config file from `r6/config/` and saves results to `r6/cache/`. A configuration file is written to `engine/config/platform/pc/input_loader.ini`, which tells the game to load the merged .xml files.\n<br />\n<br />[size=4]Usage for users[/size]\n<br />\n<br />1. Install [RED4ext](https://github.com/WopsS/RED4ext)\n<br />2. Extract the contents of input_loader.zip to your game's installation directory\n<br />\n<br />A log file will be written to `red4ext/logs/input_loader.log` every start-up, if you're having problems.\n<br />\n<br />[size=4]Node type[/size]\n<br />\n<br />Only children of `&lt;bindings&gt;` are supported currently, but they can all be in the same .xml file (to encourage a mod to have a single .xml file). Depending on the node type, the block will be added to the new `inputContexts.xml` or `inputUserMappings.xml` automatically:\n<br />    inputUserMappings.xml:\n<br />    * mapping\n<br />    * buttonGroup\n<br />    * pairedAxes\n<br />    * preset\n<br />    inputContexts.xml:\n<br />    * blend\n<br />    * context\n<br />    * hold\n<br />    * multitap\n<br />    * repeat\n<br />    * toggle\n<br />    * acceptedEvents\n<br />\n<br />[size=4]Node attributes[/size]\n<br />\n<br />You can add `append=\"true\"` to a node to avoid overwriting. This is the recommended method for adding functionality, as multiple mods will be able to do this without conflicts. See below for an example.\n<br /> \n<br />[size=4]Example .xml file[/size]\n<br />\n<br />[code]&lt;?xml version=\"1.0\"?&gt;\n<br />&lt;bindings&gt;\n<br />    &lt;!-- Defines a custom context with a custom Action, mapped to UseConsumable_Button --&gt;\n<br />    &lt;context name=\"MyCustomContext\" &gt;\n<br />        &lt;action name=\"ShakeAroundABit\" map=\"UseConsumable_Button\" /&gt;\n<br />    &lt;/context&gt;\n<br />    &lt;!-- Adds the custom context to VehicleDrive without overwriting existing definitions --&gt;\n<br />    &lt;context name=\"VehicleDrive\" append=\"true\"&gt;\n<br />        &lt;include name=\"MyCustomContext\" /&gt;\n<br />    &lt;/context&gt;\n<br />&lt;/bindings&gt;[/code]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/4575/4575-1653846065-507129799.png",
                "mod_downloads": 485483,
                "mod_unique_downloads": 323361,
                "uid": 14315126002143,
                "mod_id": 4575,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 9,
                "version": "0.0.7",
                "endorsement_count": 6839,
                "created_timestamp": 1653846080,
                "created_time": "2022-05-29T17:41:20.000+00:00",
                "updated_timestamp": 1668016732,
                "updated_time": "2022-11-09T17:58:52.000+00:00",
                "author": "Jack Humbert",
                "uploaded_by": "jackhumbert",
                "uploaded_users_profile_url": "https://nexusmods.com/users/86010988",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 86010988,
                    "member_group_id": 27,
                    "name": "jackhumbert"
                },
                "endorsement": null
            },
            {
                "name": "Virtual Atelier",
                "summary": "A framework for other modders, that allows them to add virtual stores in-game for their modded clothes items.<br />Also allows the players to preview clothing items on their characters before purchasing in stores, &amp; preview in-game items models in their inventory.",
                "description": "[b][b][size=6][color=#3c78d8]Virtual Atelier (former Vendor Preview)[/color][/size][/b]\n<br />[/b]\n<br />\n<br />[b][color=#6fa8dc][size=5]OVERVIEW\n<br />[/size][/color]\n<br />[/b][b]Virtual Atelier [/b]does a few things:\n<br />\n<br />1. Allows other modders to add in-game stores, specific for their modded items\n<br />\n<br />[img]https://i.imgur.com/GVfdLrN.jpg[/img]\n<br />\n<br />[b]CLARIFICATION, as I've been repeatedly asked about this:[/b] \n<br />    ﻿1. This mod does not allow modders to add new items, change items, update items, {whatever} items\n<br />   ﻿ 2. This is simply a way for modders to add a virtual shop, where players can easily see the modded items preview\n<br />\n<br />-----------------------------------------------------------------------------------------\n<br />\n<br />2. Allows players to preview garment on their player while shopping, before purchase\n<br />\n<br />[img]https://i.imgur.com/VDif3Up.jpg[/img]\n<br />\n<br />-----------------------------------------------------------------------------------------\n<br />\n<br />3. Adds a preview functionality for some items in player's Backpack\n<br />\n<br />[img]https://i.imgur.com/UqFILE9.jpg[/img]\n<br />\n<br />The preview functionality is based on a leftover functionality, which probably wasn't finished &amp; left disconnected in current game's version (1.31).\n<br />\n<br />-----------------------------------------------------------------------------------------\n<br />\n<br />[size=5][color=#6fa8dc][b]USAGE (FOR PLAYERS)[/b][/color]\n<br />[/size]\n<br />[b][color=#6fa8dc]Virtual Atelier Shops\n<br />[/color][/b][color=#f4f4f4]- Download a virtual store mod (or create one [see \"USAGE (FOR MODDERS)\"])\n<br />[/color]- Put it in your `r6/scripts` folder, as any other mod\n<br />- Open V's computer in his apartment &amp; enjoy\n<br />\n<br />[I've added an example shop with all clothing items in-game in files]\n<br />\n<br />[color=#6fa8dc]Vendor Shops Preview[/color]\n<br />- Press \"P\" inside any vendor shop, to open a preview window with your character's puppet.\n<br />- Click on any of the clothing items, and see how they'll look on your character right away.\n<br />- Zoom in, rotate your character, move the puppet over the screen for better preview angles (follow the button hints at the bottom of the screen)\n<br />\n<br />[b][color=#6fa8dc]Backpack Preview\n<br />[/color][/b]- Hover over an item inside your Backpack, and press \"P\" to toggle its preview widget.\n<br />\n<br />[b]NOT ALL ITEMS IN GAME HAVE PREVIEWABLE MODELS[/b].\n<br />You can preview various Consumables, Weapons &amp; some random stuff. Leaving to you to figure out what's previewable, as I didn't go over all of the existing items.\n<br />\n<br />[b][color=#6fa8dc][size=5]HOW TO UNINSTALL THE MOD[/size][/color][/b]\n<br />- Just delete Cyberpunk 2077&#92;r6&#92;scripts&#92;virtual-atelier folder as well as all Atelier shops which you have installed\n<br />\n<br />-----------------------------------------------------------------------------------------\n<br />\n<br />[b][color=#6fa8dc][size=5]USAGE (FOR MODDERS)\n<br />[/size][/color][/b][color=#f4f4f4][size=3]Hello, modder! If you want to add a custom shop, dedicated [b]specifically[/b] for your mod, follow these steps:[/size]\n<br />\n<br />[/color]1. Go over to the [b][url=https://jovial-shockley-612ec8.netlify.app/]Atelier Store Generator[/url][/b] app:\n<br />\n<br />[img]https://i.imgur.com/qTnhKbt.png[/img]\n<br />\n<br />2. Fill-in all of the required fields\n<br />3. Click \"Generate\"\n<br />4. Put the downloaded file in [b]r6/scripts[/b]\n<br />5. Visit you virtual shop in-game :)\n<br />\n<br />[img]https://i.imgur.com/4L3eHVB.png[/img]\n<br />\n<br />[img]https://i.imgur.com/P5izIa1.jpg[/img]\n<br />\n<br />﻿[img]https://i.imgur.com/mBJ7tGM.png[/img]\n<br />\n<br />-----------------------------------------------------------------------------------------\n<br />\n<br />[b][color=#6fa8dc][size=5]PRICING SYSTEM CHANGES (0.2.0)[/size][/color][/b]\n<br />[list]\n<br />[*][size=3]If the price of an item is set to 0, the proper price of the item will be caluculated to closely match the price in game. This means that weapons and clothing scale based on player level, quality, and if it's iconic. For weapons and clothing, these prices are slightly cheaper than in game. Other items scale by quality or not at all, so these prices should be identical. Had to revert the itemData object to the old way to consistantly get the base price.[/size]\n<br />[*][size=3]If the Price entry in the store's config file is missing entries, it will pad the remaining items with the price of 0.[/size]\n<br />[*][size=3]If the Price entry in the store's config file has only one value, it will pad any other items with this value.[/size]\n<br />[*][size=3]Added player level scaling for perk shards price calculation, if the price is 0 in the store's config file. Perks are harder to get in late game, so they should cost more.[/size]\n<br />[/list][size=3]\n<br />-----------------------------------------------------------------------------------------\n<br />[b][color=#6fa8dc][size=5]QUALITY DEFINITIONS CHANGES (0.2.0)[/size][/color][/b]\n<br />[list]\n<br />[*][size=3]If there is no Quality entry in the store's config file, it would make all entries Rare quality. [/size]\n<br />[*][size=3]It still does this, but now if you add only one entry, it will copy this to all items.[/size]\n<br />[/list]-----------------------------------------------------------------------------------------\n<br />[/size]\n<br />[color=#6fa8dc][size=5][b]Q&amp;A:[/b][/size][/color]\n<br />[color=#f4f4f4][size=3]1. Does the mods come with any virtual stores pre-installed?\n<br />[/size][/color]   ﻿- No, but I did add an example shop with all available clothing items in-game.\n<br />\n<br />2. I generated a custom store, but it doesn't work\n<br />   ﻿- Check that:\n<br />   ﻿   ﻿1. Your store ID must be unique, and contain only string characters (no \",[]-_ /*...\")\n<br />   ﻿   ﻿2. Provided atlas resource path exists in game's files\n<br />   ﻿   ﻿3. Provided texture part exists in atlas above   \n<br />\n<br />3. I downloaded a custom store from some other modder, and now the game crashes\n<br />   ﻿- Please take it first with the modder who created the store\n<br />\n<br />4. My \"Atelier\" tab is empty! Where are the stores?\n<br />   ﻿- This mod does not contain any virtual stores. Other modders can generate their own stores, which then will be visible with this mod.\n<br />   ﻿  You can download \"The Dream Shop\" example store from this mod's [url=https://www.nexusmods.com/cyberpunk2077/mods/2987?tab=files]Optional Files[/url] category\n<br />\n<br />5. Some items are empty when I try to preview their model in my Backpack\n<br />   ﻿- Not all items have previewable models. Nothing I can do.\n<br />\n<br />6. Some items icons are empty in the example \"The Dream Shop\" store\n<br />   ﻿- It's a random list of all clothing items I found. There's &gt;1K items, so some of them not gonna have icons.\n<br />\n<br />7. How do I transfer an item from a virtual Atelier store to my inventory?\n<br />   ﻿- Press \"P\" for purchase, while hovering over the item\n<br />\n<br />[b][color=#ff0000][size=5]!! THE MOD IS STILL WORK IN PROGRESS !![/size][/color][/b]\n<br />\n<br />[color=#6fa8dc][size=5][b]COMPATIBILITY[/b][/size][/color]\n<br />[size=4]Requires[b]:[/b][/size]\n<br />[b]redscript[/b]\n<br />\n<br />[size=4]Not compatible with[b]:[/b][/size]\n<br />[b]N/A (need some feedback from users)[/b]\n<br />\n<br />[b][color=#6fa8dc][size=5]CREDITS[/size][/color][/b]\n<br />Thanks to everyone on the \"redscript\" channel. Wouldn't have even thought about modding, if not for the awesome explanatory snippets made by [b]psiberx[/b]!\n<br />\n<br />Also thanks for help &amp; support:\n<br />- [b]jekky\n<br />[b]- [b]rfuzzo\n<br />[b][b][b]- [b]psiberx[/b][/b][/b][/b][/b][/b][/b]\n<br />- [b]Feature Bully[/b]\n<br />- [b]DJ_Kovrik[/b]\n<br />- [b]flib[/b]\n<br />- [b]Til W.[/b]\n<br />- [b]Xcellence Of Xecution\n<br />[/b]- [b]Darkcopse[/b]",
                "picture_url": "https://staticdelivery.nexusmods.com/mods/3333/images/2987/2987-1628352145-1182910865.png",
                "mod_downloads": 780610,
                "mod_unique_downloads": 372896,
                "uid": 14315126000555,
                "mod_id": 2987,
                "game_id": 3333,
                "allow_rating": true,
                "domain_name": "cyberpunk2077",
                "category_id": 5,
                "version": "0.3.1",
                "endorsement_count": 11183,
                "created_timestamp": 1628353738,
                "created_time": "2021-08-07T16:28:58.000+00:00",
                "updated_timestamp": 1665819747,
                "updated_time": "2022-10-15T07:42:27.000+00:00",
                "author": "Pacings",
                "uploaded_by": "Jesusrofls",
                "uploaded_users_profile_url": "https://nexusmods.com/users/96220198",
                "contains_adult_content": false,
                "status": "published",
                "available": true,
                "user": {
                    "member_id": 96220198,
                    "member_group_id": 30,
                    "name": "Jesusrofls"
                },
                "endorsement": null
            }
        ]
    """.trimIndent()
}
